#!/usr/bin/env bash
# Generated by CloudMind
# Azure Container Apps eco deployment script
# Target: Azure Container Apps Consumption

set -euo pipefail

RESOURCE_GROUP="rg-cloudmind-test-3s"
LOCATION="francecentral"
CONTAINER_APP_ENVIRONMENT="cae-cloudmind-test-3s"

if [ -z "${GHCR_USERNAME:-}" ]; then
  echo "Missing environment variable GHCR_USERNAME. Set it to your GitHub username, for example: Hedi808"
  exit 1
fi

if [ -z "${GHCR_TOKEN:-}" ]; then
  echo "Missing environment variable GHCR_TOKEN. Create a GitHub token with read:packages permission and set it here."
  exit 1
fi

echo "Checking Azure CLI login..."
az account show > /dev/null

echo "Installing or updating Azure Container Apps CLI extension..."
az extension add --name containerapp --upgrade

echo "Registering required Azure providers..."
az provider register --namespace Microsoft.App
az provider register --namespace Microsoft.OperationalInsights

echo "Creating resource group: $RESOURCE_GROUP"
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output table

echo "Creating Azure Container Apps environment: $CONTAINER_APP_ENVIRONMENT"
az containerapp env create \
  --name "$CONTAINER_APP_ENVIRONMENT" \
  --resource-group "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output table

echo "Deploying container app: test-3s-backend"

FQDN=$(az containerapp create \
  --name "test-3s-backend" \
  --resource-group "$RESOURCE_GROUP" \
  --environment "$CONTAINER_APP_ENVIRONMENT" \
  --image "ghcr.io/hedi808/test-3s-backend:latest" \
  --target-port 8000 \
  --ingress external \
  --min-replicas 0 \
  --max-replicas 1 \
  --cpu 0.25 \
  --memory "0.5Gi" \
  --registry-server "ghcr.io" \
  --registry-username "$GHCR_USERNAME" \
  --registry-password "$GHCR_TOKEN" \
  --query "properties.configuration.ingress.fqdn" \
  --output tsv)

echo "Application URL:"
echo "https://$FQDN"


echo "Deployment completed."
echo "Cost control: min replicas is 0, max replicas is 1, CPU is 0.25, memory is 0.5Gi."
