# Generated by CloudMind
# Azure Container Apps eco deployment script
# Target: Azure Container Apps Consumption
# OS: Windows PowerShell

$ErrorActionPreference = "Stop"

$ResourceGroup = "rg-cloudmind-test-3s"
$Location = "francecentral"
$ContainerAppEnvironment = "cae-cloudmind-test-3s"

if (-not $env:GHCR_USERNAME) {
    throw "Missing environment variable GHCR_USERNAME. Set it to your GitHub username, for example: Hedi808"
}

if (-not $env:GHCR_TOKEN) {
    throw "Missing environment variable GHCR_TOKEN. Create a GitHub token with read:packages permission and set it here."
}

Write-Host "Checking Azure CLI login..." -ForegroundColor Cyan
az account show | Out-Null

Write-Host "Installing or updating Azure Container Apps CLI extension..." -ForegroundColor Cyan
az extension add --name containerapp --upgrade

Write-Host "Registering required Azure providers..." -ForegroundColor Cyan
az provider register --namespace Microsoft.App
az provider register --namespace Microsoft.OperationalInsights

Write-Host "Creating resource group: $ResourceGroup" -ForegroundColor Cyan
az group create `
  --name $ResourceGroup `
  --location $Location `
  --output table

Write-Host "Creating Azure Container Apps environment: $ContainerAppEnvironment" -ForegroundColor Cyan
az containerapp env create `
  --name $ContainerAppEnvironment `
  --resource-group $ResourceGroup `
  --location $Location `
  --output table

Write-Host "Deploying container app: test-3s-backend" -ForegroundColor Cyan

$Fqdn = az containerapp create `
  --name "test-3s-backend" `
  --resource-group $ResourceGroup `
  --environment $ContainerAppEnvironment `
  --image "ghcr.io/hedi808/test-3s-backend:latest" `
  --target-port 8000 `
  --ingress external `
  --min-replicas 0 `
  --max-replicas 1 `
  --cpu 0.25 `
  --memory "0.5Gi" `
  --registry-server "ghcr.io" `
  --registry-username $env:GHCR_USERNAME `
  --registry-password $env:GHCR_TOKEN `
  --query "properties.configuration.ingress.fqdn" `
  --output tsv

Write-Host "Application URL:" -ForegroundColor Green
Write-Host "https://$Fqdn" -ForegroundColor Green


Write-Host "Deployment completed." -ForegroundColor Green
Write-Host "Cost control: min replicas is 0, max replicas is 1, CPU is 0.25, memory is 0.5Gi." -ForegroundColor Yellow
